# Generated by Django 4.1.3 on 2023-07-19 04:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdditiveSolution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('env', models.CharField(blank=True, choices=[('dev', 'dev'), ('test', 'test'), ('uat', 'uat'), ('pre', 'pre'), ('prod', 'prod')], default='', max_length=12, null=True, verbose_name='环境')),
                ('private_key', models.CharField(blank=True, max_length=128, null=True, verbose_name='私钥')),
                ('remark', models.CharField(blank=True, max_length=128, null=True, verbose_name='备注')),
                ('created_by', models.CharField(blank=True, default='', max_length=128, verbose_name='创建人')),
                ('date_updated', models.DateTimeField(auto_now=True, null=True, verbose_name=('更新时间',))),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name=('创建时间',))),
            ],
        ),
        migrations.CreateModel(
            name='Cloud_Secret',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('Tencent', '腾讯云'), ('Huawei', '华为云'), ('Aliyun', '阿里云')], db_index=True, default='tencent', max_length=32, verbose_name='所属云')),
                ('secretid', models.CharField(blank=True, max_length=256, null=True, verbose_name='SecretId')),
                ('secretkey', models.CharField(blank=True, max_length=256, null=True, verbose_name='SecretKey')),
                ('comment', models.TextField(blank=True, verbose_name='备注')),
                ('created_by', models.CharField(blank=True, default='', max_length=128, verbose_name='创建人')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': 'Cloud_Secret',
                'verbose_name_plural': 'Cloud_Secret',
                'ordering': ['-name'],
            },
        ),
    ]
