# Generated by Django 4.1.3 on 2023-05-19 04:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisList',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('defaultns', models.CharField(blank=True, max_length=32, null=True, verbose_name='默认记录')),
                ('line', models.CharField(blank=True, max_length=32, null=True, verbose_name='线路')),
                ('lineid', models.IntegerField(blank=True, null=True, verbose_name='线路Id')),
                ('mx', models.CharField(blank=True, max_length=32, null=True, verbose_name='MX值')),
                ('monitorstatus', models.CharField(choices=[('OK', '正常'), ('WARN', '告警'), ('DOWN', '宕机')], max_length=12, verbose_name='记录监控状态')),
                ('name', models.CharField(blank=True, max_length=64, null=True, verbose_name='主机名')),
                ('secordid', models.BigIntegerField(blank=True, null=True, verbose_name='记录Id')),
                ('remark', models.CharField(blank=True, max_length=32, null=True, verbose_name='备注')),
                ('status', models.CharField(blank=True, choices=[('ENABLE', '启用'), ('DISABLE', '暂停')], max_length=12, null=True, verbose_name='记录状态')),
                ('ttl', models.CharField(blank=True, max_length=12, null=True, verbose_name='缓存时间')),
                ('type', models.CharField(blank=True, max_length=32, null=True, verbose_name='记录类型')),
                ('updatedon', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('value', models.CharField(blank=True, max_length=32, null=True, verbose_name='记录值')),
                ('weight', models.CharField(blank=True, max_length=32, null=True, verbose_name='记录权重')),
                ('cloud', models.CharField(choices=[('Tencent', '腾讯云'), ('Huawei', '华为云'), ('Aliyun', '阿里云')], db_index=True, max_length=32, verbose_name='云')),
            ],
            options={
                'verbose_name': 'AnalysisList',
                'verbose_name_plural': 'AnalysisList',
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='DomainList',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('domainid', models.IntegerField(blank=True, null=True, verbose_name='域名标识')),
                ('effectivedns', models.CharField(blank=True, max_length=32, null=True, verbose_name='有效DNS')),
                ('isvip', models.CharField(blank=True, max_length=16, null=True, verbose_name='付费套餐')),
                ('name', models.CharField(blank=True, max_length=64, null=True, verbose_name='名称')),
                ('owner', models.CharField(blank=True, max_length=128, null=True, verbose_name='所属账号')),
                ('punycode', models.CharField(blank=True, max_length=64, null=True, verbose_name='punycode编码')),
                ('recordCount', models.IntegerField(blank=True, null=True, verbose_name='记录数量')),
                ('remark', models.CharField(blank=True, max_length=64, null=True, verbose_name='备注')),
                ('searchenginepush', models.CharField(blank=True, choices=[('Yes', '是'), ('No', '否')], max_length=64, null=True, verbose_name='搜索引擎推送优化')),
                ('status', models.CharField(blank=True, choices=[('ENABLE', '正常'), ('PAUSE', '暂停'), ('SPAM', '封禁')], max_length=12, null=True, verbose_name='状态')),
                ('createdon', models.DateTimeField(auto_now_add=True, null=True, verbose_name='添加时间')),
                ('updatedon', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('vipautorenew', models.CharField(blank=True, max_length=32, null=True, verbose_name='开通VIP自动续费')),
                ('cloud', models.CharField(choices=[('Tencent', '腾讯云'), ('Huawei', '华为云'), ('Aliyun', '阿里云')], db_index=True, max_length=32, verbose_name='云')),
            ],
            options={
                'verbose_name': 'DomainList',
                'verbose_name_plural': 'DomainList',
                'ordering': ['-name'],
            },
        ),
    ]
