# Generated by Django 4.1.3 on 2023-05-19 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0002_alter_domainlist_effectivedns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysislist',
            name='value',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='记录值'),
        ),
    ]
