# Generated by Django 4.1.3 on 2023-05-19 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0003_alter_analysislist_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysislist',
            name='lineid',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='线路Id'),
        ),
    ]
