# Generated by Django 4.1.3 on 2023-05-19 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0004_alter_analysislist_lineid'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysislist',
            name='domainid',
            field=models.IntegerField(blank=True, null=True, verbose_name='域名标识'),
        ),
    ]
