# Generated by Django 4.1.3 on 2023-05-19 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0005_analysislist_domainid'),
    ]

    operations = [
        migrations.AddField(
            model_name='domainlist',
            name='doamin_name',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='域名'),
        ),
    ]
