# Generated by Django 4.1.3 on 2023-05-19 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0007_remove_domainlist_doamin_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='analysislist',
            old_name='doamin_name',
            new_name='domain_name',
        ),
    ]
