# Generated by Django 4.1.3 on 2023-05-23 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0008_rename_doamin_name_analysislist_domain_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domainlist',
            name='domainid',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='域名标识'),
        ),
    ]
