# Generated by Django 4.1.3 on 2023-05-23 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0009_alter_domainlist_domainid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domainlist',
            name='domainid',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='域名标识'),
        ),
    ]
