# Generated by Django 4.1.3 on 2023-05-26 06:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0011_alter_analysislist_domainid'),
    ]

    operations = [
        migrations.CreateModel(
            name='DomainAudit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=128, null=True, verbose_name='域名')),
                ('cloud', models.CharField(choices=[('Tencent', '腾讯云'), ('Huawei', '华为云'), ('Aliyun', '阿里云')], db_index=True, max_length=32, verbose_name='云')),
                ('secordid', models.BigIntegerField(blank=True, null=True, verbose_name='记录Id')),
                ('source_record', models.TextField(blank=True, null=True, verbose_name='源记录')),
                ('news_record', models.TextField(blank=True, null=True, verbose_name='新记录')),
                ('action', models.CharField(blank=True, max_length=16, null=True, verbose_name='动作')),
                ('editd_by', models.CharField(blank=True, max_length=128, null=True, verbose_name='修改人')),
                ('created_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': 'DomainAudit',
                'verbose_name_plural': 'DomainAudit',
                'ordering': ['-created_time'],
            },
        ),
        migrations.AddField(
            model_name='analysislist',
            name='created_by',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='analysislist',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='analysislist',
            name='demand_by',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='需求人'),
        ),
        migrations.AddField(
            model_name='analysislist',
            name='editd_by',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='修改人'),
        ),
        migrations.AddField(
            model_name='analysislist',
            name='updated_time',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
    ]
