# Generated by Django 4.1.3 on 2023-05-26 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0012_domainaudit_analysislist_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysislist',
            name='status',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='记录状态'),
        ),
    ]
