# Generated by Django 4.1.3 on 2023-06-19 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0013_alter_analysislist_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='domainaudit',
            name='domainid',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='域名标识'),
        ),
    ]
