# Generated by Django 4.1.3 on 2023-06-20 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0014_domainaudit_domainid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analysislist',
            options={'ordering': ['-created_time'], 'verbose_name': 'AnalysisList', 'verbose_name_plural': 'AnalysisList'},
        ),
        migrations.RenameField(
            model_name='analysislist',
            old_name='secordid',
            new_name='recordid',
        ),
        migrations.RenameField(
            model_name='analysislist',
            old_name='name',
            new_name='subdomain',
        ),
    ]
