# Generated by Django 4.1.3 on 2023-06-25 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0017_rename_recordid_analysislist_secordid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='domainaudit',
            old_name='editd_by',
            new_name='created_by',
        ),
    ]
