# Generated by Django 4.1.3 on 2023-06-27 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0018_rename_editd_by_domainaudit_created_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analysislist',
            options={'ordering': ['-updatedon'], 'verbose_name': 'AnalysisList', 'verbose_name_plural': 'AnalysisList'},
        ),
    ]
