# Generated by Django 4.1.3 on 2023-06-29 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0020_alter_analysislist_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='domainlist',
            options={'ordering': ['name', '-name', models.OrderBy(models.F('recordCount'), descending=True, nulls_last=True)], 'verbose_name': 'DomainList', 'verbose_name_plural': 'DomainList'},
        ),
        migrations.AlterField(
            model_name='analysislist',
            name='remark',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='备注'),
        ),
    ]
