# Generated by Django 4.1.3 on 2023-06-30 07:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0021_alter_domainlist_options_alter_analysislist_remark'),
    ]

    operations = [
        migrations.CreateModel(
            name='CdnDomainsList',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('resourceid', models.CharField(blank=True, max_length=64, null=True, verbose_name='域名ID')),
                ('domain', models.CharField(blank=True, db_index=True, max_length=256, null=True, verbose_name='加速域名')),
                ('cname', models.CharField(blank=True, db_index=True, max_length=512, null=True, verbose_name='CNAME 地址')),
                ('status', models.CharField(choices=[('rejected', '域名审核未通过，域名备案过期/被注销导致'), ('processing', '部署中'), ('closing', '关闭中'), ('online', '已启动'), ('offline', '已关闭')], max_length=32, verbose_name='加速服务状态')),
                ('servicetype', models.CharField(choices=[('web', '静态加速'), ('download', '下载加速'), ('media', '流媒体点播加速')], max_length=32, verbose_name='业务类型')),
                ('origin', models.TextField(blank=True, null=True, verbose_name='源站配置详情')),
                ('disable', models.CharField(choices=[('normal', '正常状态'), ('overdue', '账号欠费导致域名关闭，充值完成后可自行启动加速服务'), ('malicious', '域名出现恶意行为，强制关闭加速服务'), ('ddos', '域名被大规模 DDoS 攻击，关闭加速服务'), ('idle', '域名超过 90 天内无任何操作、数据产生，判定为不活跃域名自动关闭加速服务，可自行启动加速服务'), ('unlicensed', '域名未备案 / 备案注销，自动关闭加速服务，备案完成后可自行启动加速服务'), ('capping', '触发配置的带宽阈值上限'), ('readonly', '域名存在特殊配置，被锁定')], max_length=32, verbose_name='封禁状态')),
                ('area', models.CharField(choices=[('mainland', '中国境内加速'), ('overseas', '中国境外加速'), ('global', '全球加速')], max_length=32, verbose_name='加速区域')),
                ('readonly', models.CharField(choices=[('normal', '未锁定'), ('mainland', '中国境内锁定'), ('overseas', '中国境外锁定'), ('global', '全球锁定')], max_length=32, verbose_name='锁定状态')),
                ('product', models.CharField(blank=True, max_length=16, null=True, verbose_name='所属产品')),
                ('parentHost', models.CharField(blank=True, max_length=128, null=True, verbose_name='主域名')),
                ('cloud', models.CharField(choices=[('Tencent', '腾讯云'), ('Huawei', '华为云'), ('Aliyun', '阿里云')], db_index=True, max_length=32, verbose_name='云')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'CdnDomainsList',
                'verbose_name_plural': 'CdnDomainsList',
                'ordering': ['-domain'],
            },
        ),
        migrations.AlterModelOptions(
            name='analysislist',
            options={'ordering': ['-updated_time'], 'verbose_name': 'AnalysisList', 'verbose_name_plural': 'AnalysisList'},
        ),
    ]
